### ISSUE TITLE
Successfully killed process before the end of the process

### ISSUE THREAD

**Issue by FrancoisDF** [gamunu/vscode-yarn#3] opened 2017-10-05 14:46 UTC
## Expected Behavior
The process should be completed fully even if it takes more time than expected 

## Actual Behavior
The process get killed after around 10sec of running.

## Steps to Reproduce the Problem

  1. Run a yarn process that requires longer time to compile (ex: ng cli)
  1.
  1.

## Specifications

  - Version: vscode-yarn@1.3.0
  - Platform: Mac OS
  - Subsystem:

**Comment by gamunu** [comment] 2017-10-05 17:21
hmm, interesting. It should not kill the process unless otherwise instructed. I'll find a fix for this and meantime you could try setting `"yarn.runInTerminal": true`. This should not kill the process since it's runs on terminal.

**Comment by gamunu** [comment] 2017-10-17 14:37
@R0muald I'm unable to reproduce the issue. This could happen if and only if the child process terminated with SIGTERM.

**Comment by gamunu** [comment] 2018-05-16 15:37
Is this still an issue?

**Closed** 2022-11-08 13:25 UTC
Labels: bug, help wanted
