### ISSUE TITLE
Multiple problems with multi-root workspace

### ISSUE THREAD

**Issue by tholander** [gamunu/vscode-yarn#21] opened 2020-05-04 12:20 UTC
## Expected Behavior
Everything should work fine when user is in a multi-root workspace

## Actual Behavior
Some commands like "Add ... dependency", "Run script" break for various reasons

## Steps to Reproduce the Problem

1. ```bash
    mkdir -p workspace/{first,second} && yarn init -y --cwd workspace/first && yarn init -y --cwd workspace/second
    ```
1. ```bash
    touch workspace/test.code-workspace
    ```
1. Fill the *.code-workspace with : 
    ```json
    {
      "folders": [
        {
          "path": "./first",
          "name": "first"
        },
        {
          "path": "./second",
          "name": "second"
        }
      ],
    }
    ```
1. Try to run `Add dependency` command

In the case of the `Run script` command, only the scripts of the first folder are detected, not those of the second.

## Specifications

  - Version: VSCode 1.44.2, gamunu.vscode-yarn 1.7.0
  - Platform: Windows 10

**Comment by gamunu** [comment] 2022-02-21 18:43
The issue is fixed in the release v2.0.0

**Closed by gamunu** 2022-02-21 18:43 UTC
